package behavior.State.Two.One;

public class StateApp {
    public static void main(String[] args) {
        Station dfm = new RadioDFM();
        Radio radio = new Radio();
        radio.setStation(dfm);

        for (int i = 0; i < 10; i++) {
            radio.play();
            radio.nextStation();
        }
    }
}

//Радио VestiFM...
//Радио 7...
//Радио DFM...
//Радио VestiFM...
//Радио 7...
//Радио DFM...
//Радио VestiFM...
//Радио 7...
//Радио DFM...
//Радио VestiFM...

//Радио DFM...
//Радио VestiFM...
//Радио 7...
//Радио DFM...
//Радио VestiFM...
//Радио 7...
//Радио DFM...
//Радио VestiFM...
//Радио 7...
//Радио DFM...